### PR TITLE
A few bits and pieces.

### PR DESCRIPTION
**Pull request by NimaAra**
* Enhanced the usage of `Async/Await`;
* Enabled C#7.1 on the _DemoClient_ project to allow the usage of `async Task Main()`;
* Reduced allocation;
* Fixed up _NuGet_ packaging;
* Added _NuGet_ package to the _README_;
* Some other minor refactoring.

### CODE REVIEW

**Comment by ninjasource** [comment]
Thanks for your changes!

Quick comment about ConfigureAwait(false). I know what it is used for but I see that you have made changes to a lot of awaitable function calls. Surely, if ConfigureAwait is to be used this should only be called on functions exiting the codebase (e.g. stream.ReadAsync and stream.WriteAsync) and not on all functions that ultimately make those calls?

**Comment by ninjasource** [comment]
I see that you have introduced buffer pooling to the codebase via ArrayPool<byte>. This is already in use but may not be that obvious and is opt-in. I intended for the developer to inject their own buffer pooling capabilities and an example can be seen in the demo server which uses the RecyclableMemoryStreamManager (by Microsoft). Admittedly I chose not to use this for the opening handshake since I considered this to be called far fewer times than wrting websocket frames. Thanks for pointing this out because we may have many opening handshakes.

I chose not to use pooling when reading the masking key because it is only 4 bytes in size and using an array pool for that is probably excessive since a .net heap object takes 24 bytes anyway and the byte array will fall out of scope immediately.

**Comment by NimaAra** [comment]
Every `async` method has it's own context by setting `ConfigureAwait(false)` on each `await` you are telling the _CLR_ to not capture and use that context on the continuation (it will allow the continuation to continue running in a _theadpool_ context) so yes it will have to be set for every `await`.

**Comment by NimaAra** [comment]
I agree using _ArrayPool_ for small arrays may be an overkill but when it comes to scale every allocation counts I would prefer to have less allocation as opposed to a few extra _CPU_ cycles. Of course all of this can be throttled/validated once we can do some benchmarking/profiling at scale.

**Comment by ninjasource** [comment]
One major performance improvement I have not yet made is making less calls to stream.ReadAsync (via the BinaryReaderWriter class) in the WebSocketFrameReader class. I suspect that multiple calls to this function instead on one call to fill a larger buffer incurs task related performance penalties. However, the websocket header is not fixed length because the payload length is represented differently for different size payloads. Therefore, this performance improvement needs a little thought.

**Comment by ninjasource** [comment]
A further point about the _ArrayPool_. I would prefer to continue the pattern of injecting the buffer pool technology rather than choosing one for the developer. This is currently done in the client and server factory classes (_Func<MemoryStream> recycledStreamFactory_) I also don't want to create a dependency. Notice that there are currently none. The stream factory should be passed to the HttpHelper.

btw, the stream factory avoids extra allocations and returns a stream that supports the TryGetBuffer function call which is supported for MemoryStreams and, more importantly, RecyclableMemoryStreams (_Microsoft.IO_)

**Comment by NimaAra** [comment]
Hey man, I had been thinking and I think it would make more sense for me to keep making my changes to the fork instead of raising _PRs_. 

There are more enhancements that I would like to make particularly around performance and expanding the support to include _NETSTANDARD1.3_ and _NET45_ as well as a more opinionated overall design which may not be what you are looking for.

This way you can pick and merge whichever one of my changes you find useful.

**Comment by ninjasource** [comment]
Sure man, I understand.

Just remember that there are plenty WebSocket implementations out there. I specifically wanted to implement the WebSocket abstract class that is only part of .net standard 2.0. 

I’ll be interested to see what performance gains you make. Like I said before, the major penalties I found so far are to do with task creation when the underlying network stream is read. Like all performance analysis, it is better to run actual performance tests than to pick through the codebase. You may be improving something that does not need to be improved (like using an array pool for a 4 byte buffer). Don’t take that the wrong way, any improvement is good and appreciated - except if I need to add a dependency for it! It’s a balancing act.

The Demo Client has a stress test (see complex test) there if you plan to run it on windows server under load.

**Comment by NimaAra** [comment]
I have just migrated the project to support _NETSTANDARD1.3_ and _NET45_, so now it can support even more platforms!

There is no such thing as dependency free specially when it comes to _NETSTANDARD_ the dependencies are still there but are just hidden behind the shim introduced as part of _NETSTANDARD2.0_. In the new world of _NETSTANDARD_ everything is a dependency even the collections :-)

You may be right in that the changes I make to the source before any benchmarking maybe unnecessary but I actually prefer to focus on performance right at the beginning specially when the code is still young, for me performance is a feature not an after thought therefore would need to be baked in from early on. Also these changes were quite easy to add so only took a small effort but at least when it comes to benchmarking I can focus on other areas knowing that I have closed the obvious gaps already.

Anyway for me it's more of fun exercise than anything else, let's see what good comes out of it :-)

**Pull request closed without merging**
